apiVersion: apps/v1
kind: Deployment
metadata:
  name: daratech-deployment
  labels:
    app: daratech-app
  #annotations:kubernetes.io/change-cause: ""#
spec:
  strategy:
    type: RollingUpdate # Tipos: Recreate | RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0 
  revisionHistoryLimit: 10
  replicas: 5
  selector:
    matchLabels:
      app: daratech-app
  template: 
    metadata:
      labels:
        app: daratech-app
    spec:
      containers:
      - name: daratech-container
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
