apiVersion: v1
kind: ServiceAccount
metadata:
  name: daratech-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io 
  kind: Role
  name: pod-reader
subjects: 
- kind: ServiceAccount
  name: daratech-sa
  namespace: default
