services:
  atlantis:
    build:
      context: .

    container_name: atlantis

    restart: unless-stopped

    ports:
      - "4141:4141"

    env_file:
      - .env

    volumes:
      - .:/repos
      - ./keys:/keys:ro
      - ~/.aws:/home/atlantis/.aws:ro

    working_dir: /repos

    command:
      - server
      - --repo-config=/repos/repos.yaml